language: c++
compiler: clang

dist: trusty
sudo: required

install:
  - cd $HOME
  - wget https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz -O cmake-linux.tgz
  - tar xaf cmake-linux.tgz
  - mv cmake-*-x86_64 cmake
  - mkdir -p $HOME/bin
  - ln -s $HOME/cmake/bin/cmake $HOME/bin
  - wget http://openframeworks.cc/versions/v0.9.8/of_v0.9.8_linux64_release.tar.gz
  - tar -xf of_v0.9.8_linux64_release.tar.gz
  - sudo of_v0.9.8_linux64_release/scripts/linux/ubuntu/install_dependencies.sh -y
  - of_v0.9.8_linux64_release/scripts/linux/compileOF.sh -j 8
  - cd of_v0.9.8_linux64_release/addons
  - git clone --depth=1 https://github.com/OSSIA/ofxOSSIA.git
  - cd ofxOSSIA/libs
  - ./build.sh

script:
  - cd $HOME/of_v0.9.8_linux64_release/addons/ofxOSSIA/example-simple
  - make -j 4
